version: 2
jobs:
  build:
    working_directory: ~/game-server-starter
    docker:
    - image: circleci/node:10.15.3
    - image: circleci/mysql:5.7.14
    - image: circleci/redis:5.0.5
    steps:
    - checkout
    - run:
        name: update-npm
        command: 'sudo npm install -g npm@latest'
    - run:
        name: install-npm
        command: npm install
    - save_cache: # special step to save the dependency cache
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
          - ./node_modules
    - run: # run tests
        name: test
        command: npm test
    - store_artifacts: # special step to save test results as as artifact
        # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
        path: test-results.xml
        prefix: tests
    # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples