version: 2
jobs:
  build:
    working_directory: ~/game-server-starter
    docker:
    - image: circleci/node:10.15.3
    - image: circleci/mysql:5.7.26
    - image: circleci/redis:5.0.5
    steps:
    - checkout
    - run:
        # Our primary container isn't MYSQL so run a sleep command until it's ready.
        name: Waiting for MySQL to be ready
        command: |
          for i in `seq 1 10`;
          do
          nc -z 127.0.0.1 3306 && echo Success && exit 0
          echo -n .
          sleep 1
          done
          echo Failed waiting for MySQL && exit 1
    - run:
        name: Install MySQL CLI
        command: sudo apt-get install mysql-client
    - run:
        name: Create test database
        command: mysql -h 127.0.0.1 -u root --execute="CREATE DATABASE games_test;"
    - run:
        name: update-npm
        command: 'sudo npm install -g npm@latest'
    - run:
        name: install-npm
        command: npm install
    - save_cache: # special step to save the dependency cache
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
          - ./node_modules
    - run:
        name: migrate database
        command: npm run migrate:test
    - run: # run tests
        name: test
        command: npm test
    - store_artifacts: # special step to save test results as as artifact
        # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
        path: test-results.xml
        prefix: tests
    # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples